PHD_ROOT_DIR = '/g/data/w40/ab2313/PhD'
LONGRUNMIP_DIR = PHD_ROOT_DIR + '/longrunmip'
ZECMIP_DIR = '/g/data/oi10/replicas/CMIP6/C4MIP'
DECK_DIR = '/g/data/oi10/replicas/CMIP6/CMIP'
IMAGE_SAVE_DIR = '/home/563/ab2313/Documents/images'
MODULE_DIR = '/home/563/ab2313/Documents/PhD/modules'
